### ISSUE TITLE
Stable Diffusion number options passed as strings

### ISSUE THREAD

**Issue by zolrath** [livebook-dev/kino_bumblebee#13]
If a user modifies the input options for the Stable Diffusion kino, the input options are passed on as strings.

![image](https://user-images.githubusercontent.com/454563/207975706-3ee90380-6cc9-4779-8504-5f2aa4acf039.png)

```elixir
serving =
  Bumblebee.Diffusion.StableDiffusion.text_to_image(clip, unet, vae, tokenizer, scheduler,
    num_steps: "21",
    num_images_per_prompt: "10",
    safety_checker: safety_checker,
    safety_checker_featurizer: featurizer,
    compile: [batch_size: 1, sequence_length: "51"],
    defn_options: [compiler: EXLA]
  )
```

This causes a variety of different errors depending on which options are modified as each of them are expected to be numbers.
```elixir
13:45:01.635 [error] Task #PID<0.342.0> started from Kino.DynamicSupervisor terminating
** (Axon.CompileError) exception found when compiling layer anonymous fn/2 in Axon.nx/3 named nx_0:

    ** (ArgumentError) invalid dimension in axis 1 found in shape. Each dimension must be a positive integer, got "51" in shape {2, "51"}
        (nx 0.4.1) lib/nx/shape.ex:60: Nx.Shape.validate!/3
        (nx 0.4.1) lib/nx.ex:1305: Nx.iota/2
        (bumblebee 0.1.2) lib/bumblebee/layers.ex:674: anonymous fn/2 in Bumblebee.Layers.default_position_ids/2
```

or

```elixir
14:02:11.319 [error] Task #PID<0.400.0> started from Kino.DynamicSupervisor terminating
** (ArgumentError) repetitions must be a list of integers, got: [1, "10", 1, 1]
    (nx 0.4.1) lib/nx.ex:2580: Nx.tile/2
    (bumblebee 0.1.2) lib/bumblebee/diffusion/stable_diffusion.ex:354: Bumblebee.Diffusion.StableDiffusion."__defn:text_to_image_impl__"/10
```

Is the solution to convert the numbers to strings in `to_quoted` for every model that takes inputs, or have Kino automatically convert number fields into numbers globally?

**Comment by jonatanklosko** [comment]
@zolrath thanks for the catch, it's a regression. I've just fixed this in 22fb475b912f189545dc1eea40de2e4cd0517e8b and released as v0.1.4!
